version : '3'
services:
  springappserver:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - mt-network
    volumes:
      - /data/spring
    depends_on:
      - mysqldbserver
  mysqldbserver:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - mt-network
    environment:
      MYSQL_DATABASE: survey
      MYSQL_USER: survey
      MYSQL_PASSWORD: survey
      MYSQL_ROOT_PASSWORD: survey
    container_name: survey_mysqldbserver
    volumes:
      - /data/mysql
  react:
    build: ./client
    volumes:
      - /data/react
    networks:
      - mt-network
    depends_on:
      - springappserver
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_WS_URL=springappserver
      - REACT_APP_WS_PORT=8080
networks:
  mt-network:
    driver: bridge
